### ISSUE TITLE
install JuliaRegistrator

### ISSUE THREAD

**Issue by hhaensel** [anthonyclays/RomanNumerals.jl#18]
@anthonyclays 
Could you be so kind to install the JuliaRegistrator bot by navigating to 
https://github.com/apps/juliateam-registrator/installations/new

I don't have the respective access rights. I now registered a new versions via the JuliaHub.

**Comment by anthonyclays** [comment]
I think this should be done now. Thanks!

**Comment by hhaensel** [comment]
Works like a charm!
I have merged all pull requests and closed all issues. PDFIO, that has RomanNumerals as dependency, can now be installed without problems on Julia 1.
